### ISSUE TITLE
Liquid template format % doesn't persist district changes

### ISSUE THREAD

**Issue by laurenancona** [CityOfPhiladelphia/community-health-explorer#1]
@timwis I think this is a scoping issue; since the % formatting is being done last via Liquid, it isn't triggered when Planning District is changed either by clicking map or the dropdown, since the page doesn't reload.

**Comment by timwis** [comment]
Right; it shouldn't have to. the `updateIndicators` function is what changes all the indicators. Can you point me to the line that isn't working?

**Comment by laurenancona** [comment]
[This line](https://github.com/CityOfPhiladelphia/community-health-report/blob/gh-pages/planning-districts.html#L39) begins the formatting template

**Comment by timwis** [comment]
oh, yeah. that's a tough one because the JS just replaces the contents of that DOM element entirely. Off the top of my head, we could have liquid add a `data-type` attribute to that `<h1>` tag, and have the JavaScript check if that attribute is set to `Percentage`, and then do the calculation before setting the contents of the dom element.
